FROM tomcat:9.0-jdk21-temurin

RUN rm -rf /usr/local/tomcat/webapps/*

COPY InterviewX.war /usr/local/tomcat/webapps/ROOT.war

CMD ["sh", "-c", "sed -i \"s/port=\\\"8080\\\" protocol=\\\"HTTP\\/1.1\\\"/port=\\\"${PORT:-8080}\\\" protocol=\\\"HTTP\\/1.1\\\"/\" /usr/local/tomcat/conf/server.xml && exec /usr/local/tomcat/bin/catalina.sh run"]